<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTSystemSettingsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('t_system_settings', function (Blueprint $table) {
            $table->increments('pk_i_id');
            $table->string('s_key')->unique();
            $table->string('s_value');
            $table->integer('b_enabled')->default(1);
            $table->timestamp('dt_created_date')->nullable();
            $table->dateTime('dt_modified_date')->nullable();
            $table->dateTime('dt_deleted_date')->nullable();
        });

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('t_system_settings');
    }
}
